[project]
name = "fast-alpr-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fast-alpr[onnx]>=0.3.0",
    "fastapi-mcp>=0.4.0",
    "fastapi[standard]",
    "fastmcp>=2.14.5",
    "mcp[cli]>=1.26.0",
]
